DROP TABLE Player_W;

CREATE TABLE Player_W
(
	Id						BIGINT					NOT NULL		PRIMARY KEY	IDENTITY,
	PlayerId				INTEGER					NOT NULL,
	Href					NVARCHAR(1000)			NOT NULL,
	InsertDateTime			DATETIME				DEFAULT			CURRENT_TIMESTAMP
);